operator:
  channel: stable-2.6
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: ansible-automation-platform-operator

namespace: aap

postgres:
  enabled: false
  name: aap-pgcluster
  instances: 1
  storage: 10Gi
  backupStorage: 10Gi

instance:
  enabled: true
  name: sovereign-aap

controller:
  enabled: true

eda:
  enabled: true

hub:
  enabled: true
