apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: external-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec: {}
