{{- range $es := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $es.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ $es.name }}
    creationPolicy: Owner
  data:
    {{- range $es.keys }}
    - secretKey: {{ .k8sKey }}
      remoteRef:
        key: {{ $es.remoteKey }}
        property: {{ .vaultKey }}
    {{- end }}
{{- end }}
