apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStoreName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vaultAddr | quote }}
      path: {{ .Values.vaultKvPath | quote }}
      version: v2
      auth:
        tokenSecretRef:
          name: {{ .Values.vaultTokenSecretName }}
          key: token
