{{- if .Values.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: url
    - secretKey: user
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: password
    - secretKey: cacert
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: cacert
        decodingStrategy: None
{{- end }}
