{{- if .Values.pushSecrets }}
{{- range .Values.pushSecrets }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "99"
spec:
  refreshInterval: "1h"
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ .sourceSecret }}
  data:
    {{- range .keys }}
    - conversionStrategy: None
      match:
        secretKey: {{ .secretKey }}
        remoteRef:
          remoteKey: {{ .remoteKey }}
          property: {{ .property }}
    {{- end }}
{{- end }}
{{- end }}
