apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .Values.name }}-obc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  generateBucketName: {{ .Values.name }}
  storageClassName: {{ .Values.objectStorage.bucketClassName }}
