apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  components:
    - kind: objectstorage
      managed: false
    - kind: clair
      managed: true
      overrides:
        replicas: 1
    - kind: postgres
      managed: true
    - kind: redis
      managed: true
    - kind: route
      managed: true
    - kind: tls
      managed: true
    - kind: monitoring
      managed: false
    - kind: mirror
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
    - kind: quay
      managed: true
      overrides:
        replicas: 1
  configBundleSecret: {{ .Values.name }}-config-bundle
