# RbacConfig — must be in sovereign-cloud-plugins namespace, referenced by all Rbac CRs
apiVersion: hybridsovereign.redhat/v1alpha1
kind: RbacConfig
metadata:
  name: keycloak-base
  namespace: sovereign-cloud-plugins
spec:
  keycloak:
    secret: keycloak-auth-config   # Secret with KC_URL, KC_REALM, KC_USERNAME, KC_PASSWORD
    base_path: "/"
    managed: true
