# Assignment — bridges the App tree (Team) to the Infra tree (CloudAWS)
apiVersion: hybridsovereign.redhat/v1alpha1
kind: Assignment
metadata:
  name: platform-team-to-aws
  namespace: entity-acme
spec:
  entity: acme
  ocp:
    - aws-prod
  division:
    - platform-team
  rbac:
    adminGroup:
      - acme/admins
