apiVersion: hybridsovereign.redhat/v1alpha1
kind: PlatformOpenshift
metadata:
  name: ocp-platform
  namespace: entity-acme
spec:
  entity: acme
  openshiftVersion: "4.21"
  size: small
  cloud: aws-prod
  containerRef: aws-prod
  capabilities:
    operatorGitops: true
    operatorKafka: false
    openshiftAI: false
    openshiftVirt: false
  rbac:
    adminGroup:
      - acme/admins
    developerGroup:
      - acme/developers
    readGroup: []
