apiVersion: hybridsovereign.redhat/v1alpha1
kind: Projects
metadata:
  name: app-projects
  namespace: entity-acme
spec:
  entity: acme
  capabilities:
    repo: ""
    path: ""
    gitTokenSecret: ""
