---
- name: Deliver platform secrets to services cluster
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vault_addr: "{{ lookup('env', 'VAULT_ADDR') }}"
    ocp_services_server: "{{ lookup('env', 'OCP_SERVICES_SERVER') }}"
    target_namespace: "{{ lookup('env', 'TARGET_NAMESPACE') | default('sovereign-cloud-plugins', true) }}"
  roles:
    - deliver-services-secrets
