apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.argocd.serverInsecure }}
  server:
    insecure: true
  {{- end }}
  controller:
    resources:
      limits:
        cpu: {{ .Values.argocd.controllerResources.limits.cpu | quote }}
        memory: {{ .Values.argocd.controllerResources.limits.memory | quote }}
      requests:
        cpu: {{ .Values.argocd.controllerResources.requests.cpu | quote }}
        memory: {{ .Values.argocd.controllerResources.requests.memory | quote }}
