{{- if and .Values.ociRegistry.enabled .Values.ociRegistry.token }}
apiVersion: v1
kind: Secret
metadata:
  name: quay-oci-helm-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: helm
  enableOCI: "true"
  url: {{ .Values.ociRegistry.url | quote }}
  username: {{ .Values.ociRegistry.username | quote }}
  password: {{ .Values.ociRegistry.token | quote }}
{{- end }}
