{{- if and .Values.ociRegistry.enabled .Values.ociRegistry.password }}
{{- $auth := printf "%s:%s" .Values.ociRegistry.username .Values.ociRegistry.password | b64enc }}
{{- $registryHost := .Values.ociRegistry.url | splitList "/" | first }}
{{- $dockerConfig := dict "auths" (dict $registryHost (dict "username" .Values.ociRegistry.username "password" .Values.ociRegistry.password "auth" $auth)) }}
apiVersion: v1
kind: Secret
metadata:
  name: quay-robot-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ $dockerConfig | toJson | quote }}
{{- end }}
