{{- if and .Values.github.repositoryUrl .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-git-repository
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.github.repositoryUrl | quote }}
  password: {{ .Values.github.token | quote }}
  username: {{ .Values.github.username | quote }}
  insecure: {{ .Values.github.insecure | quote }}
{{- end }}
