apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-runner
      restartPolicy: Never
      containers:
        - name: init
          image: {{ .Values.job.image | quote }}
          command:
            - /bin/bash
            - /scripts/run.sh
          env:
            - name: REPO_NS
              value: {{ .Values.repositorySecretNamespace | quote }}
            - name: REPO_NAME
              value: {{ .Values.repositorySecretName | quote }}
            - name: GIT_REVISION
              value: {{ .Values.git.revision | quote }}
            - name: MAKE_TARGETS
              value: {{ .Values.makeTargets | quote }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-script
            defaultMode: 0755
