apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: noobaa-default-bucket-class
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  placementPolicy:
    tiers:
      - backingStores:
          - noobaa-pv-backing-store
