apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamic-plugins-enabler
rules:
  - apiGroups: ["operator.openshift.io"]
    resources: ["consoles"]
    verbs: ["get", "patch", "update", "list"]
  - apiGroups: ["console.openshift.io"]
    resources: ["consoleplugins"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynamic-plugins-enabler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynamic-plugins-enabler
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ .Values.rbac.namespace }}
