apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  controller:
    disabled: {{ .Values.spec.controller.disabled }}
  eda:
    disabled: {{ .Values.spec.eda.disabled }}
    {{- if and (not .Values.spec.eda.disabled) .Values.appsDomain }}
    ingress_type: Route
    {{- end }}
  hub:
    disabled: {{ .Values.spec.hub.disabled }}
