{{- /*
SecuredCluster is created by rhacs-config PostSync job after Central is ready
and the init bundle secret has been generated. This resource depends on the
init-bundle secret which is created dynamically.
*/ -}}
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: {{ .Values.securedCluster.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterName: {{ .Values.securedCluster.clusterName }}
  centralEndpoint: {{ .Values.securedCluster.centralEndpoint | quote }}
  admissionControl:
    listenOnCreates: true
    listenOnUpdates: true
    listenOnEvents: true
  auditLogs:
    collection: Auto
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    tls:
      additionalCAs: []
