apiVersion: v2
name: custom-operators-git-creds
description: ArgoCD organisation-level credential template for the hybrid-sovereign-cloud GitHub org
type: application
version: 0.1.0
appVersion: "0.1.0"
