apiVersion: v2
name: custom-operators-pipelines
description: OpenShift Pipelines (Tekton) definitions for building all 8 custom Sovereign Cloud operator images
type: application
version: 0.1.2
appVersion: "0.1.0"
