---
vault_addr: "http://vault-active.vault.svc:8200"
vault_kv_path: "central"

services_secrets:
  - namespace: aap
    secret_name: sovereign-aap-admin-password
    vault_key: aap-services-admin
    keys:
      - password
  - namespace: aap
    secret_name: sovereign-aap-controller-admin-password
    vault_key: aap-services-controller-admin
    keys:
      - password
  - namespace: aap
    secret_name: sovereign-aap-eda-admin-password
    vault_key: aap-services-eda-admin
    keys:
      - password
  - namespace: aap
    secret_name: sovereign-aap-hub-admin-password
    vault_key: aap-services-hub-admin
    keys:
      - password
  - namespace: rhbk
    secret_name: sovereign-keycloak-services-initial-admin
    vault_key: rhbk-services-admin
    keys:
      - username
      - password
