operatorNamespace: open-cluster-management

subscription:
  name: advanced-cluster-management
  channel: release-2.16
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace

# RHACM requires a namespace-scoped OperatorGroup targeting its own namespace
operatorGroup:
  create: true
  targetNamespaces:
    - open-cluster-management
