operatorNamespace: ansible-automation-platform

subscription:
  name: ansible-automation-platform-operator
  channel: stable-2.6-cluster-scoped
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace

operatorGroup:
  create: true
  targetNamespaces: []
