{{- if .Values.instance.enabled }}
---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: {{ .Values.instance.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  {{- if .Values.gateway.enabled }}
  gateway:
    replicas: 1
  {{- end }}
  {{- if .Values.controller.enabled }}
  controller:
    replicas: 1
  {{- end }}
  {{- if .Values.eda.enabled }}
  eda:
    replicas: 1
  {{- end }}
{{- end }}
