name: central-aap

# Cluster apps domain — injected by Makefile at install time via --set appsDomain=...
appsDomain: ""

spec:
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: true
