{{- if .Values.adminCredentialsExternalSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-credentials
  namespace: {{ .Values.adminCredentialsExternalSecret.namespace | default "gitea" }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.adminCredentialsExternalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.adminCredentialsExternalSecret.secretStoreName | default "vault-backend" }}
    kind: {{ .Values.adminCredentialsExternalSecret.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.adminCredentialsExternalSecret.secretName | default "gitea-admin-credentials" }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.adminCredentialsExternalSecret.vaultPath | default "gitea-admin" }}
        metadataPolicy: None
        property: admin_user
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.adminCredentialsExternalSecret.vaultPath | default "gitea-admin" }}
        metadataPolicy: None
        property: admin_password
{{- end }}
