---
- name: Configure AAP organizations
  ansible.builtin.import_role:
    name: infra.aap_configuration.organizations

- name: Configure AAP credentials
  ansible.builtin.import_role:
    name: infra.aap_configuration.credentials

- name: Configure AAP execution environments
  ansible.builtin.import_role:
    name: infra.aap_configuration.execution_environments

- name: Configure AAP projects
  ansible.builtin.import_role:
    name: infra.aap_configuration.projects

- name: Configure AAP inventories
  ansible.builtin.import_role:
    name: infra.aap_configuration.inventories

- name: Configure AAP hosts
  ansible.builtin.import_role:
    name: infra.aap_configuration.hosts

- name: Configure AAP job templates
  ansible.builtin.import_role:
    name: infra.aap_configuration.job_templates
