apiVersion: v1
kind: ConfigMap
metadata:
  name: sovereign-cloud-info
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  role: "control-plane"
  description: "Sovereign Cloud foundation namespace"
