apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecretName | quote }}
          namespace: {{ .Values.vault.tokenSecretNamespace | quote }}
          key: {{ .Values.vault.tokenSecretKey | quote }}
