{{- range .Values.namespaces }}
{{- if .enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    app.kubernetes.io/part-of: sovereign-cloud
    app.kubernetes.io/managed-by: Helm
{{- end }}
{{- end }}
