operatorNamespace: rhacs-operator

subscription:
  name: rhacs-operator
  channel: stable
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace

# RHACS operator installs cluster-wide; no targetNamespaces needed
operatorGroup:
  create: true
  targetNamespaces: []
