---
- name: "Decode secret data for {{ result.item.vault_key }}"
  ansible.builtin.set_fact:
    decoded_data: >-
      {{
        result.item.keys | map('regex_replace', '(.+)', '\1')
        | zip(result.item.keys | map('extract', result.json.data) | map('b64decode'))
        | community.general.dict
      }}

- name: "Push {{ result.item.vault_key }} to Vault"
  ansible.builtin.uri:
    url: "{{ vault_addr }}/v1/{{ vault_kv_path }}/data/{{ result.item.vault_key }}"
    method: POST
    headers:
      X-Vault-Token: "{{ vault_token }}"
    body_format: json
    body:
      data: "{{ decoded_data }}"
    validate_certs: false
    status_code: [200, 204]
