---
- name: "Build decoded data for {{ result.item.vault_key }}"
  ansible.builtin.set_fact:
    _decoded_data: {}

- name: "Decode each key for {{ result.item.vault_key }}"
  ansible.builtin.set_fact:
    _decoded_data: "{{ _decoded_data | combine({secret_key: (result.json.data[secret_key] | b64decode)}) }}"
  loop: "{{ result.item.secret_keys }}"
  loop_control:
    loop_var: secret_key

- name: "Push {{ result.item.vault_key }} to Vault"
  ansible.builtin.uri:
    url: "{{ vault_addr }}/v1/{{ vault_kv_path }}/data/{{ result.item.vault_key }}"
    method: POST
    headers:
      X-Vault-Token: "{{ vault_token }}"
    body_format: json
    body:
      data: "{{ _decoded_data }}"
    validate_certs: false
    status_code: [200, 204]
