{{- if .Values.ociCredentials.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-oci-pull-secret
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: {{ .Values.ociCredentials.secretStoreName | quote }}
    kind: {{ .Values.ociCredentials.secretStoreKind | quote }}
  target:
    name: quay-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ `{{.registry}}` }}": {
                "username": "{{ `{{.username}}` }}",
                "password": "{{ `{{.password}}` }}",
                "auth": "{{ `{{(printf "%s:%s" .username .password) | b64enc}}` }}"
              }
            }
          }
  data:
    - secretKey: registry
      remoteRef:
        key: {{ .Values.ociCredentials.vaultPath }}
        property: registry
    - secretKey: username
      remoteRef:
        key: {{ .Values.ociCredentials.vaultPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.ociCredentials.vaultPath }}
        property: password
{{- end }}
