{{- if .Values.operatorGroup.create }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operatorNamespace }}-pipelines-og
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  targetNamespaces: {{ toYaml .Values.operatorGroup.targetNamespaces | nindent 4 }}
{{- end }}
